[package]
name = "sound-generator"
version = "0.1.0"
edition = "2021"

[dependencies]
nannou = "0.19.0"
nannou_egui = "0.19.0"
timer = "0.2.0"
chrono = "0.4.19"
midir = "0.10.1"
rand = "0.8.4"
rand_pcg = "0.3.1"
pitch_calc = "0.12.0"