use pitch_calc::*;

pub const CHROMATIC_SCALE_NOTES: &[Letter] = &[
    Letter::C,
    Letter::Csh,
    Letter::D,
    Letter::Dsh,
    Letter::E,
    Letter::F,
    Letter::Fsh,
    Letter::G,
    Letter::Gsh,
    Letter::A,
    Letter::Ash,
    Letter::B,
];
pub const MAJOR_SCALE_NOTES: &[Letter] = &[
    Letter::C,
    Letter::D,
    Letter::E,
    Letter::F,
    Letter::G,
    Letter::A,
    Letter::B,
];
pub const MINOR_SCALE_NOTES: &[Letter] = &[
    Letter::C,
    Letter::D,
    Letter::Eb,
    Letter::F,
    Letter::G,
    Letter::Ab,
    Letter::Bb,
];
pub const MAJOR_PENTATONIC_SCALE_NOTES: &[Letter] =
    &[Letter::C, Letter::D, Letter::E, Letter::G, Letter::A];
pub const MINOR_PENTATONIC_SCALE_NOTES: &[Letter] =
    &[Letter::C, Letter::Eb, Letter::F, Letter::G, Letter::Bb];

pub const INSTRUMENT_LIST: &[&str] = &[
    "Acoustic Grand Piano",
    "Bright Acoustic Piano",
    "Electric Grand Piano",
    "Honky-tonk Piano",
    "Electric Piano 1",
    "Electric Piano 2",
    "Harpsichord",
    "Clavinet",
    "Celesta",
    "Glockenspiel",
    "Music Box",
    "Vibraphone",
    "Marimba",
    "Xylophone",
    "Tubular Bells",
    "Dulcimer",
    "Drawbar Organ",
    "Percussive Organ",
    "Rock Organ",
    "Church Organ",
    "Reed Organ",
    "Accordion",
    "Harmonica",
    "Bandoneon",
    "Acoustic Guitar",
    "Acoustic Guitar",
    "Electric Guitar",
    "Electric Guitar",
    "Electric Guitar",
    "Electric Guitar",
    "Electric Guitar",
    "Electric Guitar",
    "Acoustic Bass",
    "Electric Bass",
    "Electric Bass",
    "Electric Bass",
    "Slap Bass 1",
    "Slap Bass 2",
    "Synth Bass 1",
    "Synth Bass 2",
    "Violin",
    "Viola",
    "Cello",
    "Contrabass",
    "Tremolo Strings",
    "Pizzicato Strings",
    "Orchestral Harp",
    "Timpani",
    "String Ensemble 1",
    "String Ensemble 2",
    "Synth Strings 1",
    "Synth Strings 2",
    "Choir Aahs",
    "Voice Oohs",
    "Synth Voice",
    "Orchestra Hit",
    "Trumpet",
    "Trombone",
    "Tuba",
    "Muted Trumpet",
    "French Horn",
    "Brass Section",
    "Synth Brass 1",
    "Synth Brass 2",
    "Soprano Sax",
    "Alto Sax",
    "Tenor Sax",
    "Baritone Sax",
    "Oboe",
    "English Horn",
    "Bassoon",
    "Clarinet",
    "Piccolo",
    "Flute",
    "Recorder",
    "Pan Flute",
    "Blown bottle",
    "Shakuhachi",
    "Whistle",
    "Ocarina",
    "Lead 1",
    "Lead 2",
    "Lead 3",
    "Lead 4",
    "Lead 5",
    "Lead 6",
    "Lead 7",
    "Lead 8",
    "Pad 1",
    "Pad 2",
    "Pad 3",
    "Pad 4",
    "Pad 5",
    "Pad 6",
    "Pad 7",
    "Pad 8",
    "FX 1",
    "FX 2",
    "FX 3",
    "FX 4",
    "FX 5",
    "FX 6",
    "FX 7",
    "FX 8",
    "Sitar",
    "Banjo",
    "Shamisen",
    "Koto",
    "Kalimba",
    "Bag pipe",
    "Fiddle",
    "Shanai",
    "Tinkle Bell",
    "Agogô",
    "Steel Drums",
    "Woodblock",
    "Taiko Drum",
    "Melodic Tom",
    "Synth Drum",
    "Reverse Cymbal",
    "Guitar Fret Noise",
    "Breath Noise",
    "Seashore",
    "Bird Tweet",
    "Telephone Ring",
    "Helicopter",
    "Applause",
    "Gunshot",
];
